from typing import Any

_C: Any

def _is_in_bad_fork() -> bool: ...
def manual_seed_all(seed: int) -> None: ...
def is_available() -> bool: ...
def device_count() -> int: ...
def current_device() -> int: ...
def set_device(idx: int) -> None: ...
def manual_seed(seed: int, device: int | None = None) -> None: ...
